const express = require('express');
const router = express.Router();
const Sales = require('../models/sales');

// Calculate and return the total revenue generated by all sales transactions
router.get('/total-revenue', async (req, res) => {
  try {
    const totalRevenue = await Sales.aggregate([
      {
        $group: {
          _id: null,
          total: { $sum: { $multiply: ['$quantity', '$price'] } },
        },
      },
    ]);

    res.json(totalRevenue[0]);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Internal Server Error' });
  }
});

module.exports = router;
